# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nu_wav}
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kookster"]
  s.date = %q{2012-07-19}
  s.description = %q{NuWav is a pure ruby audio WAV file parser and writer.  It supports Broadcast Wave Format (BWF), inclluding MPEG audio data, and the public radio standard cart chunk.}
  s.email = %q{andrew@beginsinwonder.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/nu_wav.rb",
    "nu_wav.gemspec",
    "test/helper.rb",
    "test/test_nu_wav.rb"
  ]
  s.homepage = %q{http://github.com/kookster/nu_wav}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{NuWav is a pure ruby audio WAV file parser and writer.}
  s.test_files = [
    "test/helper.rb",
    "test/test_nu_wav.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-mp3info>, [">= 0.6.13"])
    else
      s.add_dependency(%q<ruby-mp3info>, [">= 0.6.13"])
    end
  else
    s.add_dependency(%q<ruby-mp3info>, [">= 0.6.13"])
  end
end

